config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  post "recipes/search"
  get "recipes/:id", to: "recipes#show", as: "recipes_show"

  get "/with_react", to: "with_react#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

  scope :not_in, ->(ingredients) { where.not("qte_name ilike any (array[?])", Array(ingredients)) }
  scope :by_recipe_id, -> { group(:recipe_id).pluck(:recipe_id) }
  scope :with, -> (ingredients) { where("qte_name ilike any(Array[?])", to_list(ingredients)) }

  def self.to_list(ingredients)
    Array(ingredients).map { |name| "%#{name}%"}
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
  scope :with_ingredients, ->(ingredients) { joins(:ingredients).merge(Ingredient.with(ingredients)) }
  scope :scoring, -> { group(:id, :name).order(count: :desc).size }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ingredients = "oeufs, tomate, ciboulette, mouton, beurre, oignon, poulet"
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def search
    ingredients = (params[:ingredients] || "").split(',').map(&:strip).compact
    @recipes = RecipeFinderService.new.can_cook_with(ingredients)
    @ingredients = ingredients.join(", ")
    @nbs_ingredients = ingredients.size
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/with_react_controller.rb
class WithReactController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/with_react_helper.rb
module WithReactHelper
end

app/views/home/index.html.erb
<%- content_for :title, "Which ingredients?" -%>
<h1 class="standard">Frigo Magik</h1>

<div class="ingredient_selection">
  <%= form_with do %>
    <div>
      <%= label_tag(:ingredients, "Ingredients:") %>
      <div class="input_area">
        <%= text_area_tag(:ingredients, nil, size: "24x6") %><br />
        <div class="notice">Comma separated list of ingredients</div>
      </div>
    </div>
    <%= submit_tag("search recipes") %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frigo Magic<%= yield(:title).then { |title| ": #{title}" unless title.empty? } %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> -->
    <%= javascript_pack_tag 'index' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/search.html.erb
<%- content_for :title, "Which ingredients?" -%>
<h1 class="standard">Frigo Magik</h1>

<div class="ingredient_selection">
  <%= form_with(url: recipes_search_path) do %>
    <div>
      <%= label_tag(:ingredients, "Ingredients:") %>
      <div class="input_area">
        <%= text_area_tag(:ingredients, @ingredients, size: "24x6") %><br />
        <div class="notice">Comma separated list of ingredients</div>
      </div>
    </div>
    <%= submit_tag("search recipes") %>
  <% end %>
</div>

<div class="result standard">
  <%- if @recipes.empty? %>
    <div style="text-align: center;">
      <strong style="font-size: 25px;">No result</strong>
    </div>
  <%- else -%>
    <ul>
    <%- @recipes.each do |recipe| -%>
      <li><%= link_to(recipe.name, recipes_show_path(id: recipe.id)) %></li>
    <%- end -%>
    </ul>
  <%- end -%>
</div>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<% unless @recipe.image_url.blank? -%>
 <image src="<%= @recipe.image_url %>"/>
 <hr>
<%- end -%>

[<%= link_to("Back to search", root_path) %>]
<br />
<br />

<ul>
  <li>Author: <%= @recipe.author %></li>
  <li>Budget: <%= @recipe.budget %></li>
</ul>

<h2>Preparation</h2>

<ul>
  <%- @recipe.ingredients.each do |ingredient| -%>
    <li><%= ingredient.qte_name %></li>
  <%- end -%>
</ul>